### ISSUE TITLE
Does Not Work - WIndows 7

### ISSUE THREAD

**Issue by GGillan** [bigfive/atom-sublime-select#31]
I have installed this on Atom in Windows 7, and it seems to not work at all. Using the Alt key while holding down left-button and dragging to select, selection occurs horizontally.

Edit to add: Atom version 0.168.0

**Comment by jonnyhaynes** [comment]
Same for OSX 10.10. Looks like the latest Atom version 0.168.0 has killed it.

**Comment by braver** [comment]
Jup, seems the Shadow DOM has killed this one. @bigfive any idea how hard it would be to fix?

**Comment by GGillan** [comment]
@jonnyhaynes 
I meant the name to imply that didn't work on Windows 7, since I presumed it was working for everyone else (Linux, et al). Obviously not true. But yesterday, even before you telling me that, I noticed the type in the title (WIndows instead of Windows) and edited the post to try and change the title - can't change the title. 

I'll poke around and try again, but I think changing the title is not allowed.

**Comment by bigfive** [comment]
Wow. Yeah, just updated myself. Broken on Mac too. I'll have a look this afternoon.

**Comment by bigfive** [comment]
@GGillan Please update to 1.2.2 and see if it works for you. It looks like atom rewrote a lot of the api recently.

**Comment by jonnyhaynes** [comment]
@bigfive this is now fixed on OSX. Cheers.

**Comment by GGillan** [comment]
*@bigfive*: No - just updated and tested - still does not work on Windows 7. Tried quitting and restarting Atom after the update to be sure. Also verified also verified that 1.2.2 is the version now loaded.

**Comment by GGillan** [comment]
*@bigfive* Just an aside (there is no message or email feature in GitHub), I am unable to load the package at all on Windows 8.1. It seems that Atom has an old version of npm that GitHub no longer supports, and that version of npm barfs when trying to download an Atom package on Windows 8.1. I reported the issue to GitHub and was referred to report it to the Atom team (which I have). 

So the point is that I cannot report to you if this package works on Win 8.1 because I can't get it loaded!

**Comment by doobiwan** [comment]
Unfortunately I can confirm 1.2.2 does not work on Windows 8.1, Atom version 0.174.0.

**Comment by ipaq3115** [comment]
I think I fixed this problem. At least it worked on my machine. I put in a pull request but until then my fork is [here](https://github.com/ipaq3115/atom-sublime-select/tree/fix-on-windows)

**Comment by rbu** [comment]
Also does not work for me on Linux x64.

Duplicate of #28 ?

**Comment by gregmac** [comment]
I was also expecting alt+left on Windows, but this is not what this plugin does:

    inputCfg = switch os.platform()
      when 'darwin'
        key: 'altKey'
        mouse: 1
        middleMouse: true
      when 'linux'
        key: 'shiftKey'
        mouse: 2
        middleMouse: false
      else
        key: 'shiftKey'
        mouse: 2
        middleMouse: true

For me on Win 8.1, plugin 1.2.2 works on Atom 0.176.0 if I use middle mouse to drag (regardless of shift).

**Comment by GGillan** [comment]
On your advice just checked middleMouse (a wheel/button on mine) on Windows 7 and it works fine.

**Comment by gregmac** [comment]
Also worth noting that PR #35 fixes this (alt+left works in Windows).

**Comment by bigfive** [comment]
Ah great, so this is definitely a mouse button issue. I'll add this in now

**Comment by bigfive** [comment]
Just released a patch including the new PR. Let me know if this helps guys as I don't have a windows machine to test on

**Comment by GGillan** [comment]
Just downloaded and tested on the Windows 7 machine. I had to stop and start Atom to get it to work, but it now does work! BTW the middle mouse button click and drag also continues to work.

Thank you!
